### ISSUE TITLE
Not working with Preact's h?

### ISSUE THREAD

**Issue by neezer** [preactjs/signals#253]
- Modified the introductory example [on the Signal's documentation page](https://preactjs.com/guide/v10/signals) to use `h` instead of JSX.
- Executing directly in a browser (no compile step).

```js
import { h, render } from "https://esm.sh/preact@10.11.2";
import { signal } from "https://esm.sh/@preact/signals@1.1.2";

const count = signal(0);

function Counter() {
  return h("div", {}, [
    h("p", {}, `Count: ${count}`),
    h("button", { onClick: () => count.value++ }, "click me"),
  ]);
}

render(h(Counter), document.getElementById("app"));
```

### Expected

Clicking the button increments the counter.

### Actual

Clicking the button does nothing.

**Comment by neezer** [comment]
This might be a regression: reverting to `@preact/signals@1.1.0` works. `@preact/signals@1.1.1` breaks.

**Comment by marvinhagemeister** [comment]
Just checked and it's an error in the resolution logic of `esm.sh`. It loads two copies of Preact: `10.11.1` **and** `10.11.2`. These copies don't know about each other, which is why the counter is not updated. Forcing `esm.sh` to use the same Preact version resolves this issue.

```diff
  import { h, render } from "https://esm.sh/preact@10.11.2";
- import { signal } from "https://esm.sh/@preact/signals@1.1.2";
+ import { signal } from "https://esm.sh/@preact/signals@1.1.2?deps=preact@10.11.2";

  const count = signal(0);

  function Counter() {
    return h("div", {}, [
      h("p", {}, `Count: ${count}`),
      h("button", { onClick: () => count.value++ }, "click me"),
    ]);
  }

  render(h(Counter), document.getElementById("app"));
```

Filed an issue over at the esm.sh repo: https://github.com/ije/esm.sh/issues/442
