### ISSUE TITLE
Recursive / Dynamic signals with arrays?

### ISSUE THREAD

**Issue by yoroshikun** [preactjs/signals#258]
Sorry if the title is not descriptive, however I am having a hard time dealing with creating dynamically sized signals.
Aka: An array of signal items, and granular subscriptions to them

I have created a small reproduction of the issue along with some smaller ones in a stackblitz.

https://stackblitz.com/edit/react-ts-tz7jct?file=App.tsx

1. How to subscribe to a value that is mapped without the recursion error
2. Best way to efficiently modify an array of signals and keep reactivity
3. Best way to efficiently modify the internal signals without requiring the whole tree to re-render

Thanks in advance.

**Comment by eddyw** [comment]
It's because JSON stringify tries to serialize some internal properties of signals which are recursive.

I think signals should implement a `toJSON` method to just return the value or peek the value:
```ts
todos.__proto__.toJSON = function() {
  return this.peek();
}
```
If you do this, you can see the error will be gone and the object will be serialized correctly. Doing this (above) is a hack and should probably be implemented in the core.

> Best way to efficiently modify the internal signals without requiring the whole tree to re-render

Every component is essentially an `effect`. So you could create a `TodoItem` component and pass the single signal as a prop, this `TodoItem` is an `effect` so it'll be subscribed _only_ to the signals whose value is accessed, in this case, it can be one single todo. Kinda like:

```ts
{todos.value.map(item => <TodoItem key={item.id} todo={item} />)}
```

**Comment by yoroshikun** [comment]
Heya So i might have to rename the issue or create a new one as the bug that has been plaguing me and causing the issues that lead to this question (other than the json serialise overflow) stems from Safari Webview.

Although you will not be able to run this on safari though the stackblitz editor, this exact vite project code does not work as intended when run in safari (first spotted in tauri webview). You can see the intended behavior when running in chrome or firefox (add, wait 5s, call remove safely, visible = false, wait 300ms, remove from array)

https://stackblitz.com/edit/vitejs-vite-qdo55l?file=src/App.tsx

While all these steps seem to fire in safari, they do not seem to be updating the UI as expected.
Any assistance would be helpful
