### ISSUE TITLE
a question about Concurrent Mode

### ISSUE THREAD

**Issue by Ali1Jamal** [preactjs/signals#285]
Hello
I have a question about Concurrent Mode , I've heard that signals will have problems if i`m use it with Concurrent Mode in react 18 . is that true ? Because I'm thinking of using signals in my future projects

**Comment by blissdev** [comment]
Wonder this as well.

**Comment by rschristian** [comment]
I don't believe there is a "Concurrent mode" anymore, only "concurrent features", but best to ask the React team these sorts of questions; we have no insight on where they're going or what changes may occur in the future.

**Comment by UnknownH** [comment]
> I don't believe there is a "Concurrent mode" anymore, only "concurrent features", but best to ask the React team these sorts of questions; we have no insight on where they're going or what changes may occur in the future.

The (now ex-)react team has been [very vocal](https://github.com/facebook/react/issues/26704) about not wanting to answer anything preact-signals related, because it messes with react's internals, so you are really our only source to know if preact-signals will work with react's concurrent features, since you are the ones with supposedly enough knowledge about the React's internals to actually go and patch? them. So this statement is really the equivalent of saying "we don't know if this works or will ever work properly with react", which is like saying that preact/signals-react will never be production ready.

**Comment by rschristian** [comment]
> so you are really our only source to know if preact-signals will work with react's concurrent features

If we're talking about the future, no, unfortunately we have no idea when/if `@preact/signals-react` will require changes as that's entirely upon the React team. It's fine if they don't want to field questions about signals, it's not our intention to offload users onto them, but we cannot possibly know when or if issues will arise, as that's entirely on their side of things.

When issues arise, we'll fix them as we can. Without a road map we're stuck reacting (heh) to changes, we can't proactively make sure signals supports a yet-unreleased React version.

>  So this statement is really the equivalent of saying "we don't know if this works or will ever work properly with react"

Not at all -- it works how we wanted it to (more or less) at launch. Whether this works forever into the future, or if there are certain React features it will be mutually exclusive with, only time can tell.

Please try to remain positive and constructive. I'm not sure what sort of answer you're looking for, but this seems to be needlessly incendiary.
