### ISSUE TITLE
Unexpected error when signal value is function

### ISSUE THREAD

**Issue by yurivish** [preactjs/signals#286]
Hello! I ran into what looks like a potential Preact Signals bug earlier today –

A signal whose value is a function ends up being invoked by the library, even though no user code invokes the function.

Here's a quick example in an Observable notebook: https://observablehq.com/d/854dd2435272554a

This reproduces in CodePen too, but signing up required granting them access to read and write all my gists, which I did not want to do. Here's the code that triggers the behavior (the error is thrown):

```js
import { signal, effect } from "https://cdn.skypack.dev/@preact/signals-core@1.2.2"

const x = signal(() => {
  throw new Error("signal value was invoked as function");
});

effect(() => x.value);

x.value = null;
```

**Comment by developit** [comment]
As per `@jviide` (thanks 😄) - this isn't a bug. What's happening is that your `effect()` callback is returning `x.value`, which is a function. The return type of an effect callback is an optional cleanup function.  You'll need to use a block in your effect callback to avoid returning the signal's value.

Note that TS doesn't help here, since the type of your signal's function value happens to match the type of an effect callback (`()=>void`).  In any other case, TS would have caught this:

```ts
const x = signal((a: string) => {});

effect(() => x.value);
//           ^^^^^^^ error: (a: string) => void is not assignable to () => void
```

**Comment by yurivish** [comment]
Oh wow, that's really funny - good detective work! 😃

Thank you for the explanation (and for Preact Signals)!
