### ISSUE TITLE
Extend the API with set method to match the Svelte store contract

### ISSUE THREAD

**Issue by Thiagolino8** [preactjs/signals#299]
First of all, thank you for the library!

The .subscribe() method has already been added to the library, and it was a great addition as it makes it compatible with the svelte $ syntax using the store contract, but only the getter part of the contract was added, but it would be great also take advantage of the setter's part of the contract.
With a .set() method that behaves exactly like the setter value(), svelte can identify when a store is being assigned a new value with an = sign and uses the .set() method to assign this new value
Before the .set() method:
![Code_phmWnfAz7b](https://user-images.githubusercontent.com/84819630/215228225-07c57900-4d37-45d9-aa2d-78263c9f333c.png)

After the .set() method:
![Code_cbARcr6viN](https://user-images.githubusercontent.com/84819630/215228287-85546788-79e2-4eaa-96e7-f97fb58170a1.png)

Thanks!

**Comment by ryanatkn** [comment]
I made a demo of two other cases where this is compelling for Svelte users. The first is two-way binding a signal to an input primitive, and the second is binding a signal containing an object to a select element, which is a slightly magical convenience in Svelte.

https://svelte.dev/repl/f5870de21ef146708e51a524af1dfc17?version=3.58.0

Although I'm a Svelte user and I'd like this feature, I can see having a second way to do the same thing in such a tight library is a significant downside.

**Comment by andrewiggins** [comment]
With [Svelte 5 Runes](https://svelte.dev/blog/runes) coming, supporting & maintaining our version of Signals in Svelte is less appealing. However, has @developit [mentioned in another comment](https://github.com/preactjs/signals/pull/325#issuecomment-1620854569), anyone can easily add support for our Signals as Svelte stores themselves with the following code:

```js
import Signal from '@preact/signals-core';

Signal.prototype.set = function(value) {
  this.value = value;
};

Signal.prototype.update = function(callback) {
  this.value = callback(this.peek());
};
```

**Comment by newsve** [comment]
> With [Svelte 5 Runes](https://svelte.dev/blog/runes) coming, supporting & maintaining our version of Signals in Svelte is less appealing.

@andrewiggins There're still some reasons to still support Svelte out-of-the-box, e.g., with something like `@preact/signals-svelte`, let's call them in this thread signals-svelte: 

Svelte 4 stores eventually get deprecated, probably already in Svelte 6 (this is what Rich said between or the lines and in comments). While it is definitely not a big ask to just add @developit 's few lines above to any code base it might be still a missed opportunity.

Your signals implementation re its DX seems to be one of the cleanest out there and people might prefer it over other for different reasons in the Svelte universe:

1. Svelte 5 Runes are slick and extremely powerful but are at full of implications if you use them in the wrong way, compare [1] [2] [3]
2. Since Svelte 4 stores get deprecated users need to migrate to Runes which is a huge effort for code bases making heavy use of stores, it's often a long, complete rewrite when complex store structures have been used; not so with signal-svelte [3]
3. Also being independent of future breaking changes of Svelte and/or Runes might be quite tempting for users relying on an external lib such as signals-svelte

I am aware that doing an "official" signals-svelte by Preact could send the wrong signals in the dev community but users expressed the need to have access to lower level primitives in the past, so I wouldn't see any issues if the communication around makes clear it is just another option with different trade-offs without being better or worse.

What do you think?

[1] [Simplify $state and $derived with Decision Trees](https://github.com/sveltejs/svelte/discussions/15030)  
[2] [Non-Obvious Details About Runes](https://github.com/sveltejs/svelte/discussions/14835)  
[3] [Preact Signals > Svelte Reactivity](https://www.reddit.com/r/sveltejs/comments/15wv95d/preact_signals_svelte_reactivity/?rdt=52395)
