### ISSUE TITLE
Proposal: `untracked` api function

### ISSUE THREAD

**Issue by betula** [preactjs/signals#378]
### Untracked

Necessary to implement a function that provides a possibility for disabling the tracking of dependencies.

It has already been implemented in Angular Signals and MobX.

> Execute an arbitrary function in a non-reactive (non-tracking) context. The executed function can, optionally, return a value.
>  Angular16 docs [`untracked`](https://angular.io/api/core/untracked)

> Runs a piece of code without establishing observers.
>  MobX docs [`untracked`](https://mobx.js.org/api.html#untracked)

**What's the reason to use it?**

For reading **one signal** without dependency creation the `peek` method already implement.
[Reading signals without subscribing to them](https://preactjs.com/guide/v10/signals/#reading-signals-without-subscribing-to-them)

> On the rare occasion that you need to write to a signal inside [`effect(fn)`](https://preactjs.com/guide/v10/signals/#effectfn), but don't want the effect to re-run when that signal changes, you can use `.peek()` to get the signal's current value without subscribing.

But it is not enough.

`untracked` function provides the possibility for the `reaction` pattern:

```javascript
function reaction(sender, listener) {
  effect(() => {
    const value = sender();
    untracked(() => {
      listener(value);
    });
  }
}
```

In that pattern, you have a way to control your dependencies. The reaction will collect dependencies only from the sender function, and react only on them.

Many thanks to you, 
your signals implementation is amazing, 
I think the best at the moment.

**Comment by XantreGodlike** [comment]
I really need this functionality, too. 
In case of compositibility and easibility of usage, in some cases it's easier to use solidjs like `Accessor`
`type Accessor<T> = () => T`
Because its easy way to define lazy computation that will executed on demand. And you don't need to rely on rules of hooks. But for more flexible usage of this pattern, i need a way to turn off deps tracking on consumer side
![image](https://github.com/preactjs/signals/assets/57757211/c8fc9024-2e64-45af-a732-e0a3a5b85c78)

**Comment by XantreGodlike** [comment]
#380
