### ISSUE TITLE
Re-render doesn't work as expected using @preact/signals-react.

### ISSUE THREAD

**Issue by NehaLakma02** [preactjs/signals#463]
I thought of introducing signals in my project, watched few videos and read the documentation. Replaced one state with signal in one the files, just to test first and it doesn't work.

configuration: vite

<img width="782" alt="Screenshot 2023-12-14 at 11 08 55" src="https://github.com/preactjs/signals/assets/142504001/ae258f66-5c39-45bf-890a-581fa116f4c5">

When I click on `view geofence` modal open but in the child modal when I trigger close modal it doesn't work.

<img width="759" alt="Screenshot 2023-12-14 at 11 07 13" src="https://github.com/preactjs/signals/assets/142504001/e7e00d59-1f7a-4fe3-a831-184e45bff5b2">

[XantreGodlike](https://github.com/XantreGodlike)
[andrewiggins](https://github.com/andrewiggins)

**Comment by rschristian** [comment]
Please provide an actual, minimal reproduction -- screenshots (and collapsed ones, at that) show us no environment info or complete usage information. They're not very helpful in diagnosing an issue.

**Comment by Foorack** [comment]
Happening me as well, I believe it is because `"@preact/signals-react-transform"` is needed, and neither of us have it. I am currently looking into how to configure it with Vite, as I don't have babel.

**Comment by Foorack** [comment]
Got it working by editing `vite.config.ts`

```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		react({
			babel: {
				plugins: [['module:@preact/signals-react-transform']],
			},
		}),
	],
});
```

Also had to `npm install --save-dev @preact/signals-react-transform` (or Yarn/Bun equivalent).

**Comment by andrewiggins** [comment]
Glad to hear you got it working! Thanks for posting your fix back here.

**Comment by camstuart** [comment]
Thanks @Foorack that was exactly what I needed! This approach to state management is awesome. Great work to the preact team 👌

**Comment by codemonkeynorth** [comment]
I have a signal containing nested objects with some signal value inside those

my `$app` signal is populated in a `useLayoutEffect`
```jsx

// appSignal.ts
const $app = signal<App>() // ie can't populate it upfront

// App.tsx
const app = useApp();

useLayoutEffect(() => {
  $app.value = app 
},[app])
```

within that `app` is an object
```js
core: { 
   test: { 
      count: signal(0)
   }
}
```

even with the babel transform I find that without using `useSignals()` either of the code below won't work. 
```jsx
<div>count: {$app.value.core?.test.count ?? 0}</div>
<div>count: {$app.value.core ? $app.value.core.test.count : 0}</div>
```

I believe it's to do with the conditional render (since $app.core won't initially exist), meaning that the signal value placeholder isn't in place to begin with. 

I either have to re-rerender my component when the `$app.core` is ready, or... `useSignals()` just seems to make it work

any suggestions?

thanks.

**Comment by drahdavid** [comment]
Hi people! 

I'm starting a project from scratch. I would like to work with the signals feature from preact. Right now i can make **signals ** work locally on my host, but when i import a component from a **remote module ** that uses signals it breaks giving me this error:

![image](https://github.com/user-attachments/assets/aee54cf9-e724-4643-b53c-1c643c13afae)

This is the remote button being imported:

![image](https://github.com/user-attachments/assets/b4cf5695-8fb3-45a3-bf60-c386218a3d1f)


Here i'm importing the button from remote:

![image](https://github.com/user-attachments/assets/fe2e8167-151d-4981-bc26-d873e890bb18)

This is the vite.config for host:

![image](https://github.com/user-attachments/assets/5867a352-d8c5-4a09-b42b-49d2314ecbf9)

This is the vite.config for remote-1:

![image](https://github.com/user-attachments/assets/4d0d06ea-eb85-4ab8-b279-57a80d3f29a6)


 would really appreciate some help here, i'm out of ideas of what approach to take to solve this.

Thanks!

Things i already tried: 
- I used useState hook instead of signals in remote Button and it works ok, i can import it on host and execute setState without trouble.

**Comment by rschristian** [comment]
@drahdavid You need to use either the Babel plugin or the `useSignals()` hook, and it appears you're using neither. Please read [the instructions](https://github.com/preactjs/signals/tree/main/packages/react-transform#usage).

As for module federation, that might largely be up to you to figure out, it's not something we explicitly support and has a ton of nuance and complexity that exists outside of the library.

**Comment by drahdavid** [comment]
@rschristian Hi Ryan. Thanks for your answer. I have just updated my vite.config , on both host and remote, adding the babel plugin.
 I updated the images i uploaded previously. But the error persists. I think it's what you say, i might be up to me to figure this out. 
  Thanks !

**Comment by rschristian** [comment]
It'd be really difficult for anyone to provide further help without a minimum reproduction. Screenshots really aren't enough for us to go on.
