### ISSUE TITLE
Support React 19

### ISSUE THREAD

**Issue by Artur-** [preactjs/signals#622]
**Describe the feature you'd love to see**
React 19 was released today

**Comment by JoviDeCroock** [comment]
This not remotely sufficient for an issue, this is pretty disrespectful. What issue are you seeing implying that we _don't_ support v19

**Comment by Artur-** [comment]
Mostly based on https://github.com/preactjs/signals/issues/580#issuecomment-2195568349

The statement is quite clear

**Comment by JoviDeCroock** [comment]
So your complaint is that the peer range needs to be bumped... That could have been said 😅 honestly we do this in our free time as well, don't want to dwell on this but... yeah

**Comment by Artur-** [comment]
I think we have a small misunderstanding here. There is no complaint, there is a request to provide support for React 19 in this project.

Based on quick testing it seems that installAutoSignalTracking does not work and this is the first thing `pnpm run test` fails on (in the browser it results in `Uncaught TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')`. There was a decision in an older issue not to support it for React 19. Maybe it should be completely removed?

After that, it seems that #580 is still valid with React 19.0.0 as the tests will spit out the same error
```
    Error: A React Element from an older version of React was rendered. This is not supported. It can happen if:

    - Multiple copies of the "react" package is used.

    - A library pre-bundled an old copy of "react" or "react/jsx-runtime".
```

**Comment by Artur-** [comment]
Got something working with this, which should be compatible with React 18 also: https://github.com/Artur-/signals/commit/dc5ea891f1952009ceb094d98400402995b81753

**Comment by XantreDev** [comment]
It's easier to do this way https://github.com/XantreDev/preact-signals/blob/e814f034484c338dbbdf521cf13bcd306261c257/packages/react/src/lib/tracking.ts#L2-L7

**Comment by JoviDeCroock** [comment]
@Artur- I apologize if this comes across as a misunderstanding, from my point of view it wasn't. The issue is very low effort, we as maintainers are pretty swamped with work outside of our job, I recognise that this issue might have been well intended, however to me it did not come across that way.

The issue starts out with a blanket statement about "support react 19" without having done checks whether this is purely the peerDependency that needs to be bumped or whether there are aactual issues with the auto-runtime/transform/... when React 19 is involved.

#624 will take care of the fixes, thank you @XantreDev for doing the work in finding the `traditional.element` change - that saved me a ton of work! ❤️ 

Note that the automatic runtime is _expected_ to not work due to a lot of changes in the internal-dispatcher. We knew this ahead of time and already [added a guard](https://github.com/preactjs/signals/blob/5a02bfaac4f22459174c4695de2050d84d7b6e41/packages/react/runtime/src/auto.ts#L382-L387) and might remove the automatic runtime in the future.
