### ISSUE TITLE
unit test failed if use async method in useEffect after upgrade signal from 1.3.1 to 2.0.0

### ISSUE THREAD

**Issue by rock-57blocks** [preactjs/signals#636]
- [x] Check if updating to the latest version resolves the issue

**Environment**
- [ ] I am using `@preact/signals-core`
- [x] I am using `@preact/signals`
- [ ] I am using `@preact/signals-react`
  - [ ] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

**Describe the bug**
See code.
If I use async method to assign a value to signal in useEffect, the callback of useSignalEffect will not be executed. This issue does not exist in 1.3.1, but will appear in 2.0.0

**To Reproduce**
https://stackblitz.com/~/github.com/rock-57blocks/NeverReact?file=src/async-effect.test.tsx

- Go to [stackblitz](https://stackblitz.com/~/github.com/rock-57blocks/NeverReact)
- open terminal
- run 'npm test'

See error

**Expected behavior**
This test is passed on @preact/signals 1.3.1, but failed on 2.0.0.

**Comment by rock-57blocks** [comment]
Not sure why github.com/rock-57blocks/signals is not work with stackblitz, but it works on my local
The follow code may be more familiar to you:
@JoviDeCroock 
https://github.com/rock-57blocks/signals/blob/44748cf338d1e667a77f2403a2c1fda25208ed19/packages/preact/test/index.test.tsx#L832
![Screenshot 2024-12-30 at 15 13 59](https://github.com/user-attachments/assets/c071c88f-7e1c-43d0-9a86-cbf2583ab3cb)
```

it.only("should render src correctly", async () => {
			function App() {
				const videoRef = useRef<HTMLVideoElement>(null);
				const hlsUrl = useSignal("");

				useEffect(() => {
					const getHlsUrl = async () => {
						// this is the key issue here, if there is a promise in the useEffect, the test will fail
						const url = await new Promise<string>(resolve => {
							resolve("https://hlsurl.com/");
						});
						console.log("url changed", url);
						hlsUrl.value = url;
					};

					getHlsUrl();
				}, []);

				useSignalEffect(() => {
					console.log("call useSignalEffect with hlsUrl.value", hlsUrl.value);
					videoRef.current!.src = hlsUrl.value;
				});

				return <video data-testid="video-player" ref={videoRef}></video>;
			}

			await act(() => {
				render(<App />, scratch);
			});
			const video = scratch.firstChild as HTMLVideoElement;
			expect(video.src).to.equal("https://hlsurl.com/");
		});
```

**Comment by JoviDeCroock** [comment]
Why are you tagging me on this 😅 is this that urgent?

That being said, this looks like an expected failure to me:

- `useEffect` executes and schedules an update deferred by a micro-task
- `useSignalEffect` executes
- We leave `act`
- Value updates
- `useSignalEffect` execution is scheduled

This worked before because the update ran synchronously

**Comment by rock-57blocks** [comment]
oh sorry.
I am not very familiar with the operation of this project～
I will leave this issue here but not tag any person in the feature.

**Comment by rock-57blocks** [comment]
Even if I give up using `useSignalEffect`, the follow test is still failed.
What do you suggest if we need to call a async method in `useEffect`?

```
it.only("should render src correctly", async () => {
			function App() {
				const videoRef = useRef(null);
				const [hlsUrl, setHlsUrl] = useState("");

				useEffect(() => {
					const getHlsUrl = async () => {
						// this is the key issue here, if there is a promise in the useEffect, the test will fail
						// const url = await new Promise(resolve => {
						// 	resolve("https://hlsurl.com/");
						// });
						const url = await new Promise(resolve => {
							resolve("https://hlsurl.com/");
						});
						setHlsUrl(url);
					};

					getHlsUrl();
				}, []);

				useEffect(() => {
					console.log("call useSignalEffect with hlsUrl", hlsUrl);
					videoRef.current.src = hlsUrl;
				}, [hlsUrl]);

				return <video data-testid="video-player" ref={videoRef}></video>;
			}

			await act(() => {
				render(<App />, scratch);
			});

			/** @type {HTMLVideoElement} */
			// @ts-ignore
			const video = scratch.firstChild;
			expect(video.src).to.equal("https://hlsurl.com/");
		});
```


![Screenshot 2024-12-30 at 17 46 34](https://github.com/user-attachments/assets/8526be57-3eeb-4798-8a00-88f5a1d84212)

**Comment by JoviDeCroock** [comment]
I reckon we should not do cascading states leading to effects as a result of async operations. That can't be captured in any flushing logic, what you could do is adding some kind of 'wait' that does a setTimeout of an animation frame or mocking the async state. This used to work because signal effects were unscheduled synchronous operations which wasn't great in general

**Comment by JoviDeCroock** [comment]
I reckon we should not do cascading states leading to effects as a result of async operations. That can't be captured in any flushing logic, what you could do is adding some kind of 'wait' that does a setTimeout of an animation frame or mocking the async state. This used to work because signal effects were unscheduled synchronous operations which wasn't great in general
