### ISSUE TITLE
is it a good idea to use `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED`?

### ISSUE THREAD

**Issue by igorkamyshev** [preactjs/signals#86]
As I understand, React bindings of this package [are using `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` variable from `react` package](https://github.com/preactjs/signals/blob/main/packages/react/src/index.ts#L6).

It looks a little bit dangerous, doesn't it? It looks like it could break after any minor update of React.

[Monkey patching](https://github.com/preactjs/signals/blob/main/packages/react/src/index.ts#L105) of React internals looks are even more dangerous for me.

Is React bindings of suitable for production usage?

**Comment by Nicify** [comment]
["its-fine"](https://github.com/pmndrs/its-fine)

**Comment by trhinehart-godaddy** [comment]
Example using signals-core in React without signals-react hijacking internals via a `useSignal` util

https://codepen.io/gingur/pen/gOzaywx

**Comment by trhinehart-godaddy** [comment]
Can also use an HOC if you want to use signals in a Component Class
```js
function connectSignal(obj) {
  const entries = Object.entries(obj);
  return hoist((Component) => (props) => {
    const connectedProps = Object.fromEntries(entries.map(([key, value]) => [key, useSignal(value)]));
    return <Component { ...props } { ...connectedProps }/>
  });
}
```
https://codepen.io/gingur/pen/NWMGVdZ

**Comment by CodyJasonBennett** [comment]
`__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` is not guaranteed by the same semver as react or react-dom, but alongside internals like react-reconciler. This is why react and react-dom are updated in lock-step, with user-land implementations lagging behind to support a wide dependency range.

[pmndrs/its-fine](https://github.com/pmndrs/its-fine) abstracts Fiber internals specific to react-reconciler since I found it annoyingly common for renderer authors to leverage internal fields to support different platforms (e.g. https://github.com/facebook/react/issues/14983, https://github.com/pmndrs/react-three-fiber/issues/43). By outsourcing this to an external package, we can focus on well-supported patterns and semver for interop. Here, we control the reconciler version.

This package has a different scope though. Signals introduce a new state primitive without explicit component bindings; `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` provides the mechanism to observe components as React sees them (these are shared globals and update via rapid mutation) and invoke hooks inside the context of that component. The latter is the most error-prone part since it does not follow rules-of-hooks (you can forget to update state), but I've covered withstanding issues with this implementation in #130.

In any case, having `useSignal` accept an actual `Signal` as outlined in https://github.com/preactjs/signals/issues/86#issuecomment-1239687550 enable it to do the same thing as the bindings, with the safeguard that you're working entirely within a component. My worry for this case would be tree-shaking of component bindings -- you no longer need them. Is there a way to make this opt-in alongside a JSX transform (related: #115)?

**Comment by marvinhagemeister** [comment]
Closing this issue because with #219 the code doesn't use everyone's favorite internal property anymore 🎉

**Comment by rollie42** [comment]
@marvinhagemeister maybe I'm misunderstanding, but is it not still in use in https://github.com/preactjs/signals/blob/main/packages/react/runtime/src/auto.ts?

**Comment by ADTC** [comment]
Yeah, was super excited to use _Signals_, but I don't think my boss would approve it for our project, with a name like `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED`.

Obviously, I don't want to be 🔥d...

**Comment by swar30** [comment]
@andrewiggins if you can please clarify this topic, I see that as part of https://github.com/preactjs/signals/commit/6717601a34449080617033d93a87cc9c441a7567#diff-b36af6e1b379a3a89ec07f13fdb433bd3a8a8fa64cc8a7a7efbc20c69380efebR4 usage of __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED was re-inroduced, or moved from somewhere else in code.

where does this issue stand, are there plans to move away from using __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED ?

**Comment by XantreDev** [comment]
> @andrewiggins if you can please clarify this topic, I see that as part of https://github.com/preactjs/signals/commit/6717601a34449080617033d93a87cc9c441a7567#diff-b36af6e1b379a3a89ec07f13fdb433bd3a8a8fa64cc8a7a7efbc20c69380efebR4 usage of __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED was re-inroduced, or moved from somewhere else in code.
> 
> where does this issue stand, are there plans to move away from using __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED ?

For now it's an opt-in option for backwards compatibility. You need to use the babel plugin  with a new approach
